name: give_hope
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  onboarding_animation: ^0.0.3
  google_fonts: ^6.1.0
  onboarding: ^3.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  animations: ^2.0.8
  cloud_firestore: ^4.14.0
  hexcolor: ^3.0.1
  mask_text_input_formatter: ^2.8.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.10
  get: ^4.6.6
  csc_picker: ^0.2.7
  awesome_drawer_bar: ^1.2.0
  settings_ui: ^2.0.2
  flutter_native_splash: ^2.2.16
  email_otp: ^2.1.2
  cool_alert: ^2.0.1
  flutter_vector_icons: ^2.0.0
  image_picker: ^1.0.7
  # line_awesome_icons: ^1.0.4+2
  flutter_image_compress: ^2.0.4

  flutter_phone_direct_caller: ^2.1.1
  http: ^1.1.0
  url_launcher: ^6.2.4

  font_awesome_flutter: ^10.5.0
  line_awesome_flutter: ^2.0.0

  flutter_local_notifications: ^9.7.0
  flutter_chat_bubble: ^2.0.0
  geolocator: ^11.0.0

  share_plus: ^7.2.2
  carousel_slider: ^4.2.1
  geocoding: ^3.0.0
  flutter_email_sender: ^6.0.3
  maps_launcher: ^2.2.1
  photo_view: ^0.14.0
  app_settings: ^5.1.1
  email_auth: ^2.0.0


flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/images/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/icons/


  fonts:
    - family: CentraleSansRegular
      fonts:
        - asset: assets/CentraleSansRegular.otf
